replicaCount:  3
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.31.1"

service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  LOG_LEVEL: "info"

ingress: 
  enabled: false
  className: "nginx"
