apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL:  https://prometheus-community.github.io/helm-charts
      targetRevision: 86.2.1
      chart: kube-prometheus-stack
      helm:
        valueFiles:
        - $values-repo/platform/monitoring/values.yml
    - repoURL:  https://github.com/Mihirbhandari08/gitops-platform.git
      targetRevision: HEAD  
      ref : values-repo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
      createNamespace: true