apiVersion: argoproj.io/v1alpha1
kind:  Application
metadata:
  name: applicationsets-root
  namespace:  argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/Mihirbhandari08/gitops-platform.git
    targetRevision:  HEAD
    path: applicationsets
  destination:
      server: https://kubernetes.default.svc
      namespace: argocd
