apiVersion:  v2
name:  nginx-app
description:  nginx-server for the system
type:  application
version:  25.0.0

appVersion:  "v2.0.0"
maintainers:
  - name: devops-team
    email: devops@gmail.com
    